// Reliable car brand image map using direct Wikimedia Commons thumbnail URLs
// Format: https://commons.wikimedia.org/wiki/Special:FilePath/<filename>?width=400
const BRAND_IMG = {
  "Acura":         "acura.jpg",
  "Alfa Romeo":    "Alfa_Romeo_Giulia_2016.jpg",
  "Aston Martin":  "Aston_Martin_DB11_2016.jpg",
  "Audi":          "Audi_A4_B9_2015.jpg",
  "BMW":           "BMW_3er_G20_2019.jpg",
  "Bentley":       "Bentley_Continental_GT_2018.jpg",
  "Buick":         "Buick_Enclave_2018.jpg",
  "Cadillac":      "Cadillac_CT5_2020.jpg",
  "Chevrolet":     "Chevrolet_Camaro_2019.jpg",
  "Chrysler":      "Chrysler_300_2015.jpg",
  "Corbin":        "Corbin_Sparrow.jpg",
  "Daewoo":        "Daewoo_Lanos_2001.jpg",
  "Dodge":         "Dodge_Challenger_2018.jpg",
  "Eagle":         "Eagle_Talon_1995.jpg",
  "Ferrari":       "Ferrari_SF90_Stradale.jpg",
  "Ford":          "Ford_Mustang_2018.jpg",
  "GMC":           "GMC_Sierra_2019.jpg",
  "Geo":           "Geo_Metro_1995.jpg",
  "Holden":        "Holden_Commodore_VF.jpg",
  "Honda":         "Honda_Civic_2022.jpg",
  "Hummer":        "Hummer_H2_2003.jpg",
  "Hyundai":       "Hyundai_Sonata_2020.jpg",
  "Infiniti":      "Infiniti_Q50_2014.jpg",
  "Isuzu":         "Isuzu_D-Max_2020.jpg",
  "Jaguar":        "Jaguar_F-Type_2013.jpg",
  "Jeep":          "Jeep_Wrangler_JL_2018.jpg",
  "Kia":           "Kia_Stinger_2018.jpg",
  "Lamborghini":   "Lamborghini_Urus_2018.jpg",
  "Land Rover":    "Land_Rover_Defender_2020.jpg",
  "Lexus":         "Lexus_ES_2019.jpg",
  "Lincoln":       "Lincoln_Aviator_2020.jpg",
  "Lotus":         "Lotus_Evora_400.jpg",
  "MINI":          "MINI_Cooper_S_F56_2018.jpg",
  "Maserati":      "Maserati_Ghibli_2013.jpg",
  "Maybach":       "Mercedes-Maybach_S600_W222.jpg",
  "Mazda":         "Mazda_CX-5_2017.jpg",
  "Mercedes-Benz": "Mercedes-Benz_C-Klasse_W206.jpg",
  "Mercury":       "Mercury_Grand_Marquis_2011.jpg",
  "Mitsubishi":    "Mitsubishi_Outlander_2020.jpg",
  "Morgan":        "Morgan_Plus_4.jpg",
  "Nissan":        "Nissan_GT-R_2017.jpg",
  "Oldsmobile":    "Oldsmobile_Aurora_2001.jpg",
  "Panoz":         "Panoz_Esperante_2005.jpg",
  "Peugeot":       "Peugeot_308_2021.jpg",
  "Plymouth":      "Plymouth_Prowler_2001.jpg",
  "Pontiac":       "Pontiac_GTO_2004.jpg",
  "Porsche":       "Porsche_911_992.jpg",
  "Rolls-Royce":   "Rolls-Royce_Ghost_2021.jpg",
  "Saab":          "Saab_9-3_2008.jpg",
  "Saturn":        "Saturn_Vue_2007.jpg",
  "Scion":         "Scion_FR-S_2013.jpg",
  "Smart":         "Smart_fortwo_2015.jpg",
  "Subaru":        "Subaru_Outback_2020.jpg",
  "Suzuki":        "Suzuki_Swift_2017.jpg",
  "Tesla":         "Tesla_Model_3_2020.jpg",
  "Toyota":        "Toyota_Camry_2018.jpg",
  "Volkswagen":    "Volkswagen_Golf_GTI_Mk8.jpg",
  "Volvo":         "Volvo_XC90_2020.jpg",
};

export const getCarImageUrl = (brand = "", width = 400) => {
  const file = BRAND_IMG[brand];
  if (!file) return null;
  return `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(file)}?width=${width}`;
};
